<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->nationalities() as $index => $nationality) {
            Nationality::query()->updateOrCreate(
                ['code' => $nationality['code']],
                [
                    'name_en' => $nationality['name_en'],
                    'name_ar' => $nationality['name_ar'],
                    'is_active' => $nationality['is_active'] ?? true,
                    'available_for_project' => $nationality['available_for_project'] ?? true,
                    'available_for_director' => $nationality['available_for_director'] ?? true,
                    'available_for_international_producer' => $nationality['available_for_international_producer'] ?? true,
                    'sort_order' => $nationality['sort_order'] ?? (($index + 1) * 10),
                ],
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function nationalities(): array
    {
        return [
            [
                'code' => 'jordanian',
                'name_en' => 'Jordanian',
                'name_ar' => 'أردني',
                'sort_order' => 10,
            ],
            [
                'code' => 'international',
                'name_en' => 'International / Non-Jordanian',
                'name_ar' => 'دولي / غير أردني',
                'available_for_director' => false,
                'available_for_international_producer' => false,
                'sort_order' => 20,
            ],
            [
                'code' => 'non_jordanian',
                'name_en' => 'Non-Jordanian',
                'name_ar' => 'غير أردني',
                'available_for_project' => false,
                'sort_order' => 30,
            ],
            ['code' => 'afghan', 'name_en' => 'Afghan', 'name_ar' => 'أفغاني'],
            ['code' => 'albanian', 'name_en' => 'Albanian', 'name_ar' => 'ألباني'],
            ['code' => 'algerian', 'name_en' => 'Algerian', 'name_ar' => 'جزائري'],
            ['code' => 'american', 'name_en' => 'American', 'name_ar' => 'أمريكي'],
            ['code' => 'andorran', 'name_en' => 'Andorran', 'name_ar' => 'أندوري'],
            ['code' => 'angolan', 'name_en' => 'Angolan', 'name_ar' => 'أنغولي'],
            ['code' => 'argentine', 'name_en' => 'Argentine', 'name_ar' => 'أرجنتيني'],
            ['code' => 'armenian', 'name_en' => 'Armenian', 'name_ar' => 'أرميني'],
            ['code' => 'australian', 'name_en' => 'Australian', 'name_ar' => 'أسترالي'],
            ['code' => 'austrian', 'name_en' => 'Austrian', 'name_ar' => 'نمساوي'],
            ['code' => 'azerbaijani', 'name_en' => 'Azerbaijani', 'name_ar' => 'أذربيجاني'],
            ['code' => 'bahamian', 'name_en' => 'Bahamian', 'name_ar' => 'باهامي'],
            ['code' => 'bahraini', 'name_en' => 'Bahraini', 'name_ar' => 'بحريني'],
            ['code' => 'bangladeshi', 'name_en' => 'Bangladeshi', 'name_ar' => 'بنغلاديشي'],
            ['code' => 'barbadian', 'name_en' => 'Barbadian', 'name_ar' => 'بربادوسي'],
            ['code' => 'belarusian', 'name_en' => 'Belarusian', 'name_ar' => 'بيلاروسي'],
            ['code' => 'belgian', 'name_en' => 'Belgian', 'name_ar' => 'بلجيكي'],
            ['code' => 'belizean', 'name_en' => 'Belizean', 'name_ar' => 'بليزي'],
            ['code' => 'beninese', 'name_en' => 'Beninese', 'name_ar' => 'بنيني'],
            ['code' => 'bhutanese', 'name_en' => 'Bhutanese', 'name_ar' => 'بوتاني'],
            ['code' => 'bolivian', 'name_en' => 'Bolivian', 'name_ar' => 'بوليفي'],
            ['code' => 'bosnian_herzegovinian', 'name_en' => 'Bosnian / Herzegovinian', 'name_ar' => 'بوسني / هرزغوفيني'],
            ['code' => 'botswanan', 'name_en' => 'Botswanan', 'name_ar' => 'بوتسواني'],
            ['code' => 'brazilian', 'name_en' => 'Brazilian', 'name_ar' => 'برازيلي'],
            ['code' => 'british', 'name_en' => 'British', 'name_ar' => 'بريطاني'],
            ['code' => 'bruneian', 'name_en' => 'Bruneian', 'name_ar' => 'بروناوي'],
            ['code' => 'bulgarian', 'name_en' => 'Bulgarian', 'name_ar' => 'بلغاري'],
            ['code' => 'burkinabe', 'name_en' => 'Burkinabe', 'name_ar' => 'بوركيني'],
            ['code' => 'burundian', 'name_en' => 'Burundian', 'name_ar' => 'بوروندي'],
            ['code' => 'cambodian', 'name_en' => 'Cambodian', 'name_ar' => 'كمبودي'],
            ['code' => 'cameroonian', 'name_en' => 'Cameroonian', 'name_ar' => 'كاميروني'],
            ['code' => 'canadian', 'name_en' => 'Canadian', 'name_ar' => 'كندي'],
            ['code' => 'cape_verdean', 'name_en' => 'Cape Verdean', 'name_ar' => 'رأسي أخضري'],
            ['code' => 'central_african', 'name_en' => 'Central African', 'name_ar' => 'أفريقي أوسطي'],
            ['code' => 'chadian', 'name_en' => 'Chadian', 'name_ar' => 'تشادي'],
            ['code' => 'chilean', 'name_en' => 'Chilean', 'name_ar' => 'تشيلي'],
            ['code' => 'chinese', 'name_en' => 'Chinese', 'name_ar' => 'صيني'],
            ['code' => 'colombian', 'name_en' => 'Colombian', 'name_ar' => 'كولومبي'],
            ['code' => 'comoran', 'name_en' => 'Comoran', 'name_ar' => 'قمري'],
            ['code' => 'congolese', 'name_en' => 'Congolese', 'name_ar' => 'كونغولي'],
            ['code' => 'costa_rican', 'name_en' => 'Costa Rican', 'name_ar' => 'كوستاريكي'],
            ['code' => 'croatian', 'name_en' => 'Croatian', 'name_ar' => 'كرواتي'],
            ['code' => 'cuban', 'name_en' => 'Cuban', 'name_ar' => 'كوبي'],
            ['code' => 'cypriot', 'name_en' => 'Cypriot', 'name_ar' => 'قبرصي'],
            ['code' => 'czech', 'name_en' => 'Czech', 'name_ar' => 'تشيكي'],
            ['code' => 'danish', 'name_en' => 'Danish', 'name_ar' => 'دنماركي'],
            ['code' => 'djiboutian', 'name_en' => 'Djiboutian', 'name_ar' => 'جيبوتي'],
            ['code' => 'dominican', 'name_en' => 'Dominican', 'name_ar' => 'دومينيكي'],
            ['code' => 'dutch', 'name_en' => 'Dutch', 'name_ar' => 'هولندي'],
            ['code' => 'ecuadorean', 'name_en' => 'Ecuadorean', 'name_ar' => 'إكوادوري'],
            ['code' => 'egyptian', 'name_en' => 'Egyptian', 'name_ar' => 'مصري'],
            ['code' => 'emirati', 'name_en' => 'Emirati', 'name_ar' => 'إماراتي'],
            ['code' => 'equatorial_guinean', 'name_en' => 'Equatorial Guinean', 'name_ar' => 'غيني استوائي'],
            ['code' => 'eritrean', 'name_en' => 'Eritrean', 'name_ar' => 'إريتري'],
            ['code' => 'estonian', 'name_en' => 'Estonian', 'name_ar' => 'إستوني'],
            ['code' => 'ethiopian', 'name_en' => 'Ethiopian', 'name_ar' => 'إثيوبي'],
            ['code' => 'fijian', 'name_en' => 'Fijian', 'name_ar' => 'فيجي'],
            ['code' => 'filipino', 'name_en' => 'Filipino', 'name_ar' => 'فلبيني'],
            ['code' => 'finnish', 'name_en' => 'Finnish', 'name_ar' => 'فنلندي'],
            ['code' => 'french', 'name_en' => 'French', 'name_ar' => 'فرنسي'],
            ['code' => 'gabonese', 'name_en' => 'Gabonese', 'name_ar' => 'غابوني'],
            ['code' => 'gambian', 'name_en' => 'Gambian', 'name_ar' => 'غامبي'],
            ['code' => 'georgian', 'name_en' => 'Georgian', 'name_ar' => 'جورجي'],
            ['code' => 'german', 'name_en' => 'German', 'name_ar' => 'ألماني'],
            ['code' => 'ghanaian', 'name_en' => 'Ghanaian', 'name_ar' => 'غاني'],
            ['code' => 'greek', 'name_en' => 'Greek', 'name_ar' => 'يوناني'],
            ['code' => 'grenadian', 'name_en' => 'Grenadian', 'name_ar' => 'غرينادي'],
            ['code' => 'guatemalan', 'name_en' => 'Guatemalan', 'name_ar' => 'غواتيمالي'],
            ['code' => 'guinean', 'name_en' => 'Guinean', 'name_ar' => 'غيني'],
            ['code' => 'guyanese', 'name_en' => 'Guyanese', 'name_ar' => 'غياني'],
            ['code' => 'haitian', 'name_en' => 'Haitian', 'name_ar' => 'هايتي'],
            ['code' => 'honduran', 'name_en' => 'Honduran', 'name_ar' => 'هندوراسي'],
            ['code' => 'hungarian', 'name_en' => 'Hungarian', 'name_ar' => 'هنغاري'],
            ['code' => 'icelandic', 'name_en' => 'Icelandic', 'name_ar' => 'آيسلندي'],
            ['code' => 'indian', 'name_en' => 'Indian', 'name_ar' => 'هندي'],
            ['code' => 'indonesian', 'name_en' => 'Indonesian', 'name_ar' => 'إندونيسي'],
            ['code' => 'iranian', 'name_en' => 'Iranian', 'name_ar' => 'إيراني'],
            ['code' => 'iraqi', 'name_en' => 'Iraqi', 'name_ar' => 'عراقي'],
            ['code' => 'irish', 'name_en' => 'Irish', 'name_ar' => 'أيرلندي'],
            ['code' => 'italian', 'name_en' => 'Italian', 'name_ar' => 'إيطالي'],
            ['code' => 'ivorian', 'name_en' => 'Ivorian', 'name_ar' => 'إيفواري'],
            ['code' => 'jamaican', 'name_en' => 'Jamaican', 'name_ar' => 'جامايكي'],
            ['code' => 'japanese', 'name_en' => 'Japanese', 'name_ar' => 'ياباني'],
            ['code' => 'kazakh', 'name_en' => 'Kazakh', 'name_ar' => 'كازاخستاني'],
            ['code' => 'kenyan', 'name_en' => 'Kenyan', 'name_ar' => 'كيني'],
            ['code' => 'kuwaiti', 'name_en' => 'Kuwaiti', 'name_ar' => 'كويتي'],
            ['code' => 'kyrgyz', 'name_en' => 'Kyrgyz', 'name_ar' => 'قيرغيزستاني'],
            ['code' => 'laotian', 'name_en' => 'Laotian', 'name_ar' => 'لاوسي'],
            ['code' => 'latvian', 'name_en' => 'Latvian', 'name_ar' => 'لاتفي'],
            ['code' => 'lebanese', 'name_en' => 'Lebanese', 'name_ar' => 'لبناني'],
            ['code' => 'liberian', 'name_en' => 'Liberian', 'name_ar' => 'ليبيري'],
            ['code' => 'libyan', 'name_en' => 'Libyan', 'name_ar' => 'ليبي'],
            ['code' => 'lithuanian', 'name_en' => 'Lithuanian', 'name_ar' => 'ليتواني'],
            ['code' => 'luxembourgish', 'name_en' => 'Luxembourgish', 'name_ar' => 'لوكسمبورغي'],
            ['code' => 'malaysian', 'name_en' => 'Malaysian', 'name_ar' => 'ماليزي'],
            ['code' => 'maldivian', 'name_en' => 'Maldivian', 'name_ar' => 'مالديفي'],
            ['code' => 'malian', 'name_en' => 'Malian', 'name_ar' => 'مالي'],
            ['code' => 'maltese', 'name_en' => 'Maltese', 'name_ar' => 'مالطي'],
            ['code' => 'mauritanian', 'name_en' => 'Mauritanian', 'name_ar' => 'موريتاني'],
            ['code' => 'mauritian', 'name_en' => 'Mauritian', 'name_ar' => 'موريشيوسي'],
            ['code' => 'mexican', 'name_en' => 'Mexican', 'name_ar' => 'مكسيكي'],
            ['code' => 'moldovan', 'name_en' => 'Moldovan', 'name_ar' => 'مولدوفي'],
            ['code' => 'monacan', 'name_en' => 'Monacan', 'name_ar' => 'موناكي'],
            ['code' => 'mongolian', 'name_en' => 'Mongolian', 'name_ar' => 'منغولي'],
            ['code' => 'montenegrin', 'name_en' => 'Montenegrin', 'name_ar' => 'مونتينيغري'],
            ['code' => 'moroccan', 'name_en' => 'Moroccan', 'name_ar' => 'مغربي'],
            ['code' => 'mozambican', 'name_en' => 'Mozambican', 'name_ar' => 'موزمبيقي'],
            ['code' => 'namibian', 'name_en' => 'Namibian', 'name_ar' => 'ناميبي'],
            ['code' => 'nepalese', 'name_en' => 'Nepalese', 'name_ar' => 'نيبالي'],
            ['code' => 'new_zealander', 'name_en' => 'New Zealander', 'name_ar' => 'نيوزيلندي'],
            ['code' => 'nicaraguan', 'name_en' => 'Nicaraguan', 'name_ar' => 'نيكاراغوي'],
            ['code' => 'nigerian', 'name_en' => 'Nigerian', 'name_ar' => 'نيجيري'],
            ['code' => 'norwegian', 'name_en' => 'Norwegian', 'name_ar' => 'نرويجي'],
            ['code' => 'omani', 'name_en' => 'Omani', 'name_ar' => 'عماني'],
            ['code' => 'pakistani', 'name_en' => 'Pakistani', 'name_ar' => 'باكستاني'],
            ['code' => 'palestinian', 'name_en' => 'Palestinian', 'name_ar' => 'فلسطيني'],
            ['code' => 'panamanian', 'name_en' => 'Panamanian', 'name_ar' => 'بنمي'],
            ['code' => 'paraguayan', 'name_en' => 'Paraguayan', 'name_ar' => 'باراغواياني'],
            ['code' => 'peruvian', 'name_en' => 'Peruvian', 'name_ar' => 'بيروفي'],
            ['code' => 'polish', 'name_en' => 'Polish', 'name_ar' => 'بولندي'],
            ['code' => 'portuguese', 'name_en' => 'Portuguese', 'name_ar' => 'برتغالي'],
            ['code' => 'qatari', 'name_en' => 'Qatari', 'name_ar' => 'قطري'],
            ['code' => 'romanian', 'name_en' => 'Romanian', 'name_ar' => 'روماني'],
            ['code' => 'russian', 'name_en' => 'Russian', 'name_ar' => 'روسي'],
            ['code' => 'rwandan', 'name_en' => 'Rwandan', 'name_ar' => 'رواندي'],
            ['code' => 'saudi', 'name_en' => 'Saudi', 'name_ar' => 'سعودي'],
            ['code' => 'senegalese', 'name_en' => 'Senegalese', 'name_ar' => 'سنغالي'],
            ['code' => 'serbian', 'name_en' => 'Serbian', 'name_ar' => 'صربي'],
            ['code' => 'singaporean', 'name_en' => 'Singaporean', 'name_ar' => 'سنغافوري'],
            ['code' => 'slovak', 'name_en' => 'Slovak', 'name_ar' => 'سلوفاكي'],
            ['code' => 'slovenian', 'name_en' => 'Slovenian', 'name_ar' => 'سلوفيني'],
            ['code' => 'somali', 'name_en' => 'Somali', 'name_ar' => 'صومالي'],
            ['code' => 'south_african', 'name_en' => 'South African', 'name_ar' => 'جنوب أفريقي'],
            ['code' => 'south_korean', 'name_en' => 'South Korean', 'name_ar' => 'كوري جنوبي'],
            ['code' => 'spanish', 'name_en' => 'Spanish', 'name_ar' => 'إسباني'],
            ['code' => 'sri_lankan', 'name_en' => 'Sri Lankan', 'name_ar' => 'سريلانكي'],
            ['code' => 'sudanese', 'name_en' => 'Sudanese', 'name_ar' => 'سوداني'],
            ['code' => 'swedish', 'name_en' => 'Swedish', 'name_ar' => 'سويدي'],
            ['code' => 'swiss', 'name_en' => 'Swiss', 'name_ar' => 'سويسري'],
            ['code' => 'syrian', 'name_en' => 'Syrian', 'name_ar' => 'سوري'],
            ['code' => 'taiwanese', 'name_en' => 'Taiwanese', 'name_ar' => 'تايواني'],
            ['code' => 'tajik', 'name_en' => 'Tajik', 'name_ar' => 'طاجيكي'],
            ['code' => 'tanzanian', 'name_en' => 'Tanzanian', 'name_ar' => 'تنزاني'],
            ['code' => 'thai', 'name_en' => 'Thai', 'name_ar' => 'تايلندي'],
            ['code' => 'tunisian', 'name_en' => 'Tunisian', 'name_ar' => 'تونسي'],
            ['code' => 'turkish', 'name_en' => 'Turkish', 'name_ar' => 'تركي'],
            ['code' => 'turkmen', 'name_en' => 'Turkmen', 'name_ar' => 'تركماني'],
            ['code' => 'ugandan', 'name_en' => 'Ugandan', 'name_ar' => 'أوغندي'],
            ['code' => 'ukrainian', 'name_en' => 'Ukrainian', 'name_ar' => 'أوكراني'],
            ['code' => 'uruguayan', 'name_en' => 'Uruguayan', 'name_ar' => 'أوروغواياني'],
            ['code' => 'uzbek', 'name_en' => 'Uzbek', 'name_ar' => 'أوزبكي'],
            ['code' => 'venezuelan', 'name_en' => 'Venezuelan', 'name_ar' => 'فنزويلي'],
            ['code' => 'vietnamese', 'name_en' => 'Vietnamese', 'name_ar' => 'فيتنامي'],
            ['code' => 'yemeni', 'name_en' => 'Yemeni', 'name_ar' => 'يمني'],
            ['code' => 'zambian', 'name_en' => 'Zambian', 'name_ar' => 'زامبي'],
            ['code' => 'zimbabwean', 'name_en' => 'Zimbabwean', 'name_ar' => 'زيمبابوي'],
        ];
    }
}
